### ISSUE TITLE
[manage-freeserver]ネザーのワールドボーダーに衝突時マグマに入ってしまう

### ISSUE THREAD

**Issue by Alpha9n** [freeserverproject/manage-freeserver#14]
## 概要
資源ネザーにおいてブランチマイニング中、細い通路を掘っていた際発生
ワールドボーダーの外に出ようとした際ボーダー内に引き戻され、マグマ溜まりにテレポートさせられた。

**Comment by graycat27** [comment]
事象再現性確認しました
録画を元に事象を確認したところ、ワープ先は「近くのマグマ溜まり」ではなく、「初期地付近のマグマ溜まり」でした
https://youtu.be/bBKKH83ym0M
移動先の座標： 17 30 4

**Comment by graycat27** [comment]
ワープ先の現場確認しました
`warp ネザー資源ワールド` で遷移する先の4マス下のようです
この場所は厚さ2のネザーラックの地盤があるだけで、そこより下はマグマでした
![2024-11-27_21 37 52](https://github.com/user-attachments/assets/e3d7e145-9c71-4f6f-a1d1-ffe718ed8df8)

**Comment by kosukej** [comment]
本件テレポート先の整備・保護のみで暫定の処理としては問題ないという認識で良いですか？

**Comment by graycat27** [comment]
上記暫定処置で問題ないと思います

**Comment by tererun** [comment]
処置しましたー
